### ISSUE TITLE
EXEC_BAD_ACCESS requestNextAdWithDelaySeconds on self.lastRequestTime

### ISSUE THREAD

**Issue by saetia** [deltaDNA/ios-smartads-sdk#2]
this is happening to me about every 3rd launch.

![xcoe](https://cloud.githubusercontent.com/assets/869498/16363667/79bcde12-3b97-11e6-9143-306ef3440964.png)

self	DDNASmartAdAgent *	0x15c2721c0	0x000000015c2721c0
NSObject	NSObject	
_adWasClicked	BOOL	NO	false
_adLeftApplication	BOOL	NO	false
_delegate	id	0x0	0x0000000000000000
_decisionPoint	NSString *	nil	0x0000000000000000
_state	DDNASmartAdAgentState	DDNASmartAdAgentStateLoading
_currentAdapter	DDNASmartAdMoPubAdapter *	0x15c271170	0x000000015c271170
_adsShown	NSInteger	0
_lastAdShownTime	NSDate *	nil	0x0000000000000000
_lastRequestTime	__NSDate *	2016-06-26 16:52:18 UTC	0x00000001576c9590
_waterfall	DDNASmartAdWaterfall *	0x15c2711d0	0x000000015c2711d0
_viewController	UIViewController *	nil	0x0000000000000000
_adapterIndex	NSInteger	0
delaySeconds	NSUInteger	0

**Comment by dwxw** [comment]
I've still never been able to replicate this problem.  The delegate has been set to nil, which is why it crashes.  But the delegate is supposed to be the AdService, so I'm unsure why that would disappear.  Could you send a basic XCode project that exhibits this problem to support@deltadna.com so I can take a look?

**Comment by saetia** [comment]
i was removing the deltadna delegate viewcontroller from the navigation stack. my fault
